### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by serbanmarti** [xxpxxxxp/intellij-plugin-golangci-lint#1]
Hello,

I cannot seem to configure this properly in Goland in order to make it work at all. I only have the executable path configured and nothing else. Once it starts running, it just throws an error:

```
java.lang.Throwable: Run error: level=warning msg="Failed to discover go env: failed to run 'go env': exec: \"go\": executable file not found in $PATH"
level=error msg="Running error: context loading failed: failed to load program with go/packages: 'go list' driver requires 'go', but executable file not found in $PATH"

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.ypwang.plugin.GoLinterLocalInspection.checkFile(GoLinterLocalInspection.kt:134)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:142)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$8(LocalInspectionsPass.java:319)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:169)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$9(LocalInspectionsPass.java:318)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Is there anything in particular that I have to do for it? Thanks

**Comment by xxpxxxxp** [comment]
wow I'm sorry this plugin is still in development, so I've only published it to alpha channel, I guess you search in google that direct you here.
For your situation, I guess you need to set up your Go executable in system PATH. Since you are using GoLand, Go should already in system, but you need to add its bin path in system PATH.
Remember that it's still alpha testing. Some problems I'm still fixing.

**Comment by serbanmarti** [comment]
Yes, I found your work through searches and I definitely know and understand this is an alpha version. Just wanted to let you know of the issue I found in hopes that it will help you in your work on it. I am really looking forward to using your plugin 😃

**Comment by wilfred-s** [comment]
Same issue, file watcher sets the environment:
```
    <envs>
      <env name="PATH" value="$GoBinDirs$" />
      <env name="GOROOT" value="$GOROOT$" />
      <env name="GOPATH" value="$GOPATH$" />
    </envs>
```
The `$GoBinDirs$` is set correctly and has the go binary on the path that is set

**Comment by JDiPierro** [comment]
Same issue. I've tried manually setting `GOROOT` and `GOPATH` in the File Watcher's Environment Variables section and it's still unable to find the `go` bin.
