### ISSUE TITLE
Error with Go 1.19 and golangci-lint 1.47.3

### ISSUE THREAD

**Issue by niallnsec** [xxpxxxxp/intellij-plugin-golangci-lint#116]
When attempting to configure the linter after installing Golang 1.19, I am getting the following exception:

```
java.lang.Exception: Incompatible golangci-lint with Go1.18, please update to version after 1.45.0
	at com.ypwang.plugin.GolangCiOutputParser.parseLinters(GolangCiOutputParser.kt:40)
	at com.ypwang.plugin.form.GoLinterSettings.lambda$initializeLinters$18(GoLinterSettings.java:388)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by xxpxxxxp** [comment]
Does the issue still happen? And what's the platform BTW?

**Comment by niallnsec** [comment]
This appears to be fixed in the latest update, thank you very much for the quick fix!

And the platform was macOS arm64

**Comment by xxpxxxxp** [comment]
Thanks for confirming!
