### ISSUE TITLE
Throwing exception

### ISSUE THREAD

**Issue by lmtyler** [xxpxxxxp/intellij-plugin-golangci-lint#132]
GoLand 2022.2.5
Build #GO-222.4459.23, built on November 21, 2022
Licensed to Walmart.com / Michael Tyler
Subscription is active until May 20, 2023.
Runtime version: 17.0.5+7-b469.71 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Metal Rendering is ON
Registry:
    ide.intellij.laf.enable.animation=true
    suggest.all.run.configurations.from.context=true
    ide.completion.variant.limit=500
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.4)
    com.mallowigi.idea (18.1.0)
    cn.haojiyou.CodeGlance3 (2.1.1-2021.1.3)
    YAML/Ansible support (0.11.2)
    mobi.hsz.idea.gitignore (4.4.2)
    com.ypwang.plugin.go-linter (1.6.2)
    com.mallowigi (73.0.0)

Go Linter (1.6.2)

```
java.lang.NullPointerException: Cannot invoke "javax.swing.JPanel.getLayout()" because "this.linterSelectPanel" is null
	at com.ypwang.plugin.form.GoLinterConfigurable.initializeLinters(GoLinterConfigurable.java:369)
	at com.ypwang.plugin.form.GoLinterConfigurable.linterSelected(GoLinterConfigurable.java:580)
	at java.desktop/javax.swing.JComboBox.fireActionEvent(JComboBox.java:1294)
	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:619)
	at com.ypwang.plugin.form.GoLinterConfigurable$4.lambda$run$1(GoLinterConfigurable.java:258)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:513)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:75)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:118)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by lmtyler** [comment]
unfortunately, I have been able to reproduce at will, just that it has multiple times in the last few days so I thought I should report it.

**Comment by reesmanp** [comment]
Happening to me as well. Seems to be consistent whenever I close a file, the go linter crashes.

**Comment by reesmanp** [comment]
Not sure if this is relevant, but I just found this error when changing windows back to Goland:
```
/Users/me/go/bin/golangci-lint run --disable=typecheck /Users/me/workspace/repo/v1
level=warning msg="[runner] Can't run linter goanalysis_metalinter: buildir: failed to load package goarch: could not load export data: no export data for \"internal/goarch\""
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: buildir: failed to load package goarch: could not load export data: no export data for \"internal/goarch\"\n\n"
```

**Comment by lmtyler** [comment]
I have been able to replicate it.
I get this every time I open a GoLand project that does not have golangci-lint already configured within the project.
It does not matter if I have it configured in the plugins and File Watchers.
It seems to require it at the project level every time and then if not there is throws this error

**Comment by xxpxxxxp** [comment]
Got it, thanks! will look into the issue soon.

**Comment by charleskorn** [comment]
I'm also seeing this issue in IntelliJ Ultimate 2022.3.

**Comment by rahulmysore23** [comment]
> I have been able to replicate it. I get this every time I open a GoLand project that does not have golangci-lint already configured within the project. It does not matter if I have it configured in the plugins and File Watchers. It seems to require it at the project level every time and then if not there is throws this error

I'm seeing the same issue. The golangci-lint is configured at the project level

**Comment by xxpxxxxp** [comment]
Closing this as the issue should be fixed in latest release. Feel free to ping me if not.
