### ISSUE TITLE
java.lang.IllegalStateException: There is no ProgressIndicator or Job in this thread, the current job is not cancellable.

### ISSUE THREAD

**Issue by 808codist** [xxpxxxxp/intellij-plugin-golangci-lint#159]
GoLand 2024.1
Build #GO-241.14494.238, built on March 27, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 16384M
Cores: 16
Registry:
  debugger.new.tool.window.layout=true
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=true
  ide.experimental.ui=true
  go.run.processes.with.pty=false
Non-Bundled Plugins:
  com.intellij.lang.puppet (241.14494.150)
  PythonCore (241.14494.240)
  org.intellij.plugins.hcl (241.14494.150)
  IdeaVIM (2.10.2)
  com.ypwang.plugin.go-linter (1.6.6)

###### 1st Exception
```
java.lang.IllegalStateException: There is no ProgressIndicator or Job in this thread, the current job is not cancellable.
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:128)
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:126)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:83)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:126)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:121)
	at com.intellij.execution.wsl.WslIjentUtil.fetchLoginShellEnv(WslIjentUtil.kt:34)
	at com.intellij.execution.wsl.WSLDistribution.getEnvironment(WSLDistribution.java:518)
	at com.ypwang.plugin.platform.WSL.getEnvMap(WSL.kt:45)
	at com.ypwang.plugin.platform.WSL.runProcess(WSL.kt:57)
	at com.ypwang.plugin.form.GoLinterConfigurable.lambda$initializeLinters$14(GoLinterConfigurable.java:389)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
![image](https://github.com/xxpxxxxp/intellij-plugin-golangci-lint/assets/963723/5ec05b5c-72c2-4a0c-befc-52bc6b1a9c22)

###### 2nd Exception
```
java.lang.IllegalStateException: There is no ProgressIndicator or Job in this thread, the current job is not cancellable.
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:128)
	at com.intellij.openapi.progress.CoroutinesKt$runBlockingCancellable$1.invoke(coroutines.kt:126)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:83)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:126)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:121)
	at com.intellij.execution.wsl.WslIjentUtil.runProcessBlocking(WslIjentUtil.kt:62)
	at com.intellij.execution.wsl.WSLDistribution.lambda$patchCommandLine$2(WSLDistribution.java:239)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:490)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:463)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:356)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:86)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:46)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:20)
	at com.intellij.execution.wsl.WSLDistribution.executeOnWsl(WSLDistribution.java:190)
	at com.ypwang.plugin.platform.WSL.runProcess(WSL.kt:52)
	at com.ypwang.plugin.form.GoLinterConfigurable.lambda$initializeLinters$14(GoLinterConfigurable.java:389)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by xxpxxxxp** [comment]
Thanks @808codist , to confirm, this exception throws when used with WSL on Windows, right?

**Comment by davejbax** [comment]
I'm running into the same issue, and can confirm I'm using WSL2 on Windows (10). I'm using GoLand 2024.1 and Go Linter 1.6.6

**Comment by 808codist** [comment]
> Thanks @808codist , to confirm, this exception throws when used with WSL on Windows, right?

Confirmed.

**Comment by sergunya** [comment]
Hi! 

As you may have already read on the main page of this project, the GoLand team will take care of the plugin and its further development from now on. For convenience and consistency, we have moved all open tickets for this plugin from GitHub to the open bug tracker of the GoLand product (here is a link to [this ticket](https://youtrack.jetbrains.com/issue/GO-17594/java.lang.IllegalStateException-There-is-no-ProgressIndicator-or-Job-in-this-thread-the-current-job-is-not-cancellable)). 

We will soon analyze all the issues and plan to work on them. Feel free to open a new ticket or leave comments on existing ones.
