### ISSUE TITLE
configure golangci-lint got InvalidPathException error

### ISSUE THREAD

**Issue by sicay1** [xxpxxxxp/intellij-plugin-golangci-lint#16]
i am using windows, goland 2019.3.1

Here is stacktrace.txt
java.nio.file.InvalidPathException: Illegal char <:> at index 11: C:\Python27:\python.exe\golangci-lint.exe
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.ypwang.plugin.form.GoLinterSettings.getLinterFromPath(GoLinterSettings.java:239)
	at com.ypwang.plugin.form.GoLinterSettings.createUIComponents(GoLinterSettings.java:151)
	at com.ypwang.plugin.form.GoLinterSettings.$$$setupUI$$$(GoLinterSettings.java)
	at com.ypwang.plugin.form.GoLinterSettings.<init>(GoLinterSettings.java:79)
	at com.ypwang.plugin.GoLinterSettingsTracker$projectOpened$1.run(GoLinterSettingsTracker.kt:20)
	at com.intellij.notification.NotificationAction.lambda$createSimple$0(NotificationAction.java:44)
	at com.intellij.notification.NotificationAction$1.actionPerformed(NotificationAction.java:36)
	at com.intellij.notification.NotificationAction.actionPerformed(NotificationAction.java:25)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:298)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:315)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:289)
	at com.intellij.notification.Notification.fire(Notification.java:237)
	at com.intellij.notification.EventLog$2.hyperlinkUpdate(EventLog.java:149)
	at com.intellij.notification.EventLog$NotificationHyperlinkInfo.navigate(EventLog.java:582)
	at com.intellij.execution.impl.EditorHyperlinkSupport.lambda$getLinkNavigationRunnable$0(EditorHyperlinkSupport.java:155)
	at com.intellij.execution.impl.EditorHyperlinkSupport$1.mouseReleased(EditorHyperlinkSupport.java:84)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseReleasedCommand(EditorImpl.java:3790)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:3693)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:846)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:778)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by xxpxxxxp** [comment]
@sicay1 Do you have a PATH env like `C:\Python27:\python.exe`?
You can check you PATH by run `echo %PATH%` in CMD.

**Comment by sicay1** [comment]
![2020-04-10 22_02_32-Window](https://user-images.githubusercontent.com/23693701/79000640-32184f00-7b77-11ea-9f30-d7f77146ce48.png)

Hi @xxpxxxxp, thank you help,
I already add python path, and update Go Linter 1.3.3, i think problem illegal char ":"

**Comment by sicay1** [comment]
ah i saw system variable PATH C:\Python27:\python.exe. Fixed.

**Comment by xxpxxxxp** [comment]
Thank you for confirming. ':' isn't a legal char for windows path, I'm surprised MS allows to add such path to PATH.
