### ISSUE TITLE
java.lang.Throwable: Argument rangeInElement (3132,3132) endOffset must not exceed descriptor text range (0, 3130) length (3130).

### ISSUE THREAD

**Issue by nebiros** [xxpxxxxp/intellij-plugin-golangci-lint#17]
The code:

```go
package heap

type heap struct {
	xs []int
}

func (h *heap) len() int {
	return len(h.xs) - 1
}

func (h *heap) insert(x int) {
	(*h).xs = append(h.xs, x)
}

func (h *heap) bubbleUp(i int) {
	parentIndex, found := h.parentIndex(i)
	if !found {
		return
	}

	if h.xs[parentIndex] > h.xs[i] {
		h.xs[i], h.xs[parentIndex] = h.xs[parentIndex], h.xs[i]
		h.bubbleUp(parentIndex)
	}
}

func (h *heap) parentIndex(i int) (int, bool) {
	if i == 1 {
		return 0, false
	}

	return i / 2, true
}

func (h *heap) leftIndex(i int) int {
	return 2 * i
}

func (h *heap) rightIndex(i int) int {
	return 2*i + 1
}

func main() {

}
```

The exception:

```
java.lang.Throwable: Argument rangeInElement (3132,3132) endOffset must not exceed descriptor text range (0, 3130) length (3130).
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.codeInspection.ProblemDescriptorBase.<init>(ProblemDescriptorBase.java:67)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:95)
	at com.ypwang.plugin.GoLinterLocalInspection.matchAndShow(GoLinterLocalInspection.kt:465)
	at com.ypwang.plugin.GoLinterLocalInspection.checkFile(GoLinterLocalInspection.kt:153)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:141)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:60)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:320)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:168)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:110)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:320)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:117)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by xxpxxxxp** [comment]
Thanks @nebiros , I'll fix it in next release.

**Comment by xxpxxxxp** [comment]
@nebiros please check if the issue still exists, thanks.

**Comment by xxpxxxxp** [comment]
@nebiros haven't heard from you for 2 weeks, I'll close this but feel free to reopen it if the issue still presents.
