### ISSUE TITLE
ArrayOutOfBounds

### ISSUE THREAD

**Issue by profgsindel** [xxpxxxxp/intellij-plugin-golangci-lint#3]
```
java.lang.ArrayIndexOutOfBoundsException: 2 >= 2
	at java.base/java.util.Vector.elementAt(Vector.java:496)
	at java.desktop/javax.swing.table.DefaultTableColumnModel.getColumn(DefaultTableColumnModel.java:295)
	at com.ypwang.plugin.form.GoLinterSettings.lambda$refreshLinterTable$1(GoLinterSettings.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by xxpxxxxp** [comment]
Thanks @profgsindel , how could I reproduce this bug? Which buttons have you clicked?

**Comment by profgsindel** [comment]
None - except configure the path the the golintci executable. This occurs on the "out of the box" configuration on my 2019.2.3 IntelliJ on Mac OS.

________________________________

**Comment by xxpxxxxp** [comment]
Thanks @profgsindel . Apparently I missed some exception, I'll try on my Mac.

**Comment by Ramseyyj** [comment]
the similar problem occurs to me after I installed it and run the "go get ..." botton 

```
java.lang.ArrayIndexOutOfBoundsException: 0 >= 0
	at java.base/java.util.Vector.removeElementAt(Vector.java:579)
	at java.desktop/javax.swing.table.DefaultTableColumnModel.removeColumn(DefaultTableColumnModel.java:152)
	at java.desktop/javax.swing.JTable.createDefaultColumnsFromModel(JTable.java:1293)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4391)
	at java.desktop/javax.swing.JTable.setModel(JTable.java:3693)
	at com.intellij.ui.table.JBTable.setModel(JBTable.java:281)
	at com.ypwang.plugin.form.GoLinterSettings.lambda$refreshLinterTable$1(GoLinterSettings.java:134)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by xxpxxxxp** [comment]
@Ramseyyj I'm working on refine the plugin, will fix it ASAP.

**Comment by xxpxxxxp** [comment]
Resolved.
