### ISSUE TITLE
not working with goland 2019.3.2 and go 1.13.6 (homebrew)

### ISSUE THREAD

**Issue by helmus** [xxpxxxxp/intellij-plugin-golangci-lint#7]
After installing `golangci-lint` with homebrew and configuring it in goland, I get this error

```
$ tail -f idea.log
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
2020-02-26 20:06:57,286 [  21010]   WARN -                      go-linter - Run error: level=warning msg="Failed to discover go env: failed to run 'go env': exec: \"go\": executable file not found in $PATH"
level=error msg="Running error: context loading failed: failed to load program with go/packages: 'go list' driver requires 'go', but executable file not found in $PATH"
. Usually it's caused by wrongly configured parameters or corrupted with config file.
2020-02-26 20:06:57,810 [  21534]   WARN -                      go-linter - Run error: level=warning msg="Failed to discover go env: failed to run 'go env': exec: \"go\": executable file not found in $PATH"
level=error msg="Running error: context loading failed: failed to load program with go/packages: 'go list' driver requires 'go', but executable file not found in $PATH"
. Usually it's caused by wrongly configured parameters or corrupted with config file.
```
Using go 1.13.6, also installed with homebrew 
GoLand version ( installed with jetbrains toolbox )
```
GoLand 2019.3.2
Build #GO-193.6015.58, built on February 3, 2020
Runtime version: 11.0.5+10-b520.30 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: run.processes.with.pty=TRUE, ide.completion.variant.limit=500, debugger.watches.in.variables=false, suggest.all.run.configurations.from.context=true, folding.check.collapse.state.before.placeholder.text=TRUE, ideFeaturesTrainer.welcomeScreen.tutorialsTree=TRUE
Non-Bundled Plugins: AWSCloudFormation, BashSupport, com.ypwang.plugin.go-linter, name.kropp.intellij.makefile, net.ashald.envfile, org.intellij.plugins.hcl, org.zalando.intellij.swagger, ru.adelf.idea.dotenv
```

**Comment by xxpxxxxp** [comment]
Thank you @helmus ! I will fix that ASAP.

**Comment by helmus** [comment]
@xxpxxxxp after installing go with official installed, and installing golangci-lint to gopath, this is still not working.

**Comment by xxpxxxxp** [comment]
@helmus Sorry I can't repro the issue, I need your help, would you please paste result of:
go executable path: `which go`
GoLand's path env: `ps eww -o command <GoLand PID> | tr ' ' '\n' | grep '^PATH='`

**Comment by rumstead** [comment]
Getting the same issue here but with Intellij.
```
2020-02-27 16:33:06,730 [4910120]   INFO - .script.IdeScriptEngineManager - javax.script.ScriptEngineManager initialized in 264 ms
2020-02-27 16:34:50,065 [5013455]   INFO - ndex.PrebuiltIndexProviderBase - Prebuilt sdk-stubs indices are missing for go
2020-02-27 16:34:50,344 [5013734]   WARN -                      go-linter - Run error: level=warning msg="Failed to discover go env: failed to run 'go env': exec: \"go\": executable file not found in $PATH"
level=error msg="Running error: context loading failed: failed to load program with go/packages: 'go list' driver requires 'go', but executable file not found in $PATH"
. Usually it's caused by wrongly configured parameters or corrupted with config file.
2020-02-27 16:34:53,926 [5017316]   WARN -                      go-linter - Run error: level=warning msg="Failed to discover go env: failed to run 'go env': exec: \"go\": executable file not found in $PATH"
```
Go and golangci-lint from homebrew. Intellij from the Jetbrains toolbar.
```
go env
GO111MODULE=""
GOARCH="amd64"
GOBIN="<valid path to go bin>"
GOCACHE="<valid path to go build>"
GOENV="<valid path to go env>"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="<valid path to go>"

which go
/usr/local/bin/go

ps eww -o command <pid> | tr ' ' '\n' | grep '^PATH='
PATH=/usr/bin:/bin:/usr/sbin:/sbin
```
The intellij path obviously isn't my path when I launch a terminal. 
https://depressiverobot.com/2016/02/05/intellij-path.html

**Comment by xxpxxxxp** [comment]
Thanks @rumstead , seams exactly the issue. Changing Intellij's env is tricky, I'll add a workaround to use Go plugin's executable path.

**Comment by xxpxxxxp** [comment]
I've fixed the problem in the last commit, the plugin update will be ready in 2 days.
Thanks @helmus @rumstead for your help.

**Comment by rumstead** [comment]
Thank you!

**Comment by JCzz** [comment]
Same problem in:

Goland: 2021.3
go version go1.17.3 darwin/arm64

**Comment by xxpxxxxp** [comment]
Hi @JCzz  please open a new issue with some details, like Goland error log and your `go env`.
