### ISSUE TITLE
ClassNotFoundException: org.apache.commons.io.IOUtils

### ISSUE THREAD

**Issue by Pheric** [xxpxxxxp/intellij-plugin-golangci-lint#8]
I got this exception, but I do not know what I was doing when it occurred: I found it today, but it occurred yesterday (potentially while installing this plugin). This exception has occurred once.

Plugin version: 1.1.6
GoLand version: 2019.3.2
Go version: go1.13.8
Platform: Linux / amd64

Exception:
```
java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
	at com.ypwang.plugin.UtilitiesKt.fetchLatestGoLinter(Utilities.kt:81)
	at com.ypwang.plugin.form.GoLinterSettings.lambda$goGet$12(GoLinterSettings.java:406)
	at com.intellij.openapi.progress.impl.CoreProgressManager$1.run(CoreProgressManager.java:219)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$4(ApplicationImpl.java:441)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:209)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.IOUtils PluginClassLoader[com.ypwang.plugin.go-linter, 1.1.6] com.intellij.ide.plugins.cl.PluginClassLoader@7054579e
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 19 more
```

EDIT: This has happened twice more, around the same time.

**Comment by xxpxxxxp** [comment]
Thanks @Pheric . Apache common-io suppose to be an bundled library, I'll check if JetBrains removed that dependency from GoLand.

**Comment by xxpxxxxp** [comment]
The problem is caused by Intellij & GoLand bundled different commons-io library (honestly I don't know why they do this). I've removed the correspond API usage, version 1.2.2 should be working now.
@Pheric repo step is: Settings - Tools - Go Linter - Get Latest
