### ISSUE TITLE
加载完成后打开报下面的错误

### ISSUE THREAD

**Issue by workwb** [xxpxxxxp/intellij-plugin-golangci-lint#89]
java.lang.Exception: Failed to Discover Linters: RunProcessResult(returnCode=2, stdout=, stderr=panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.9()
	github.com/go-critic/go-critic@v0.6.1/checkers/checkers.go:58 +0x4b4
)
	at com.ypwang.plugin.GolangCiOutputParser.parseLinters(GolangCiOutputParser.kt:34)
	at com.ypwang.plugin.form.GoLinterSettings.lambda$initializeLinters$17(GoLinterSettings.java:384)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by xxpxxxxp** [comment]
这是一个来自上游linter gocritic的bug，只能等他们修好，可能下个版本的golangci-lint就可以了
https://github.com/go-critic/go-critic/issues/1157
https://github.com/go-critic/go-critic/issues/1126

暂时可以先disable gocritic来解决

**Comment by workwb** [comment]
好的！
