### ISSUE TITLE
Failed to Discover Linters Exception

### ISSUE THREAD

**Issue by zcyc** [xxpxxxxp/intellij-plugin-golangci-lint#96]
java.lang.Exception: Failed to Discover Linters: RunProcessResult(returnCode=1, stdout=, stderr=2021/12/29 15:57:30 Can't get enabled linters: unknown linters: 'ddd', run 'golangci-lint help linters' to see the list of supported linters
)
	at com.ypwang.plugin.GolangCiOutputParser.parseLinters(GolangCiOutputParser.kt:34)
	at com.ypwang.plugin.form.GoLinterSettings.lambda$initializeLinters$17(GoLinterSettings.java:384)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by zcyc** [comment]
![image](https://user-images.githubusercontent.com/9925064/147641246-da780a2d-b4e0-4523-b5b1-f8bdf4a8bf58.png)
![image](https://user-images.githubusercontent.com/9925064/147641274-8c0394d1-7b47-4932-8e9a-922d5fd18c7a.png)

**Comment by xxpxxxxp** [comment]
`GOROOT` 如果最近更新过GO SDK，比如通过 `brew upgrade` 或者 apt 等等形式，需要**重启一下IDE**，plugin就可以找到正确的地址了。
```Can't get enabled linters: unknown linters: 'ddd', run 'golangci-lint help linters' to see the list of supported linters``` 应该没有ddd这个linter，找找看conf里是不是写错了，去掉就可以了

**Comment by zcyc** [comment]
您好，我的 ddd 是个自定义扫描器，最近确实更新过 GO SDK，重启 IDE 不生效，我重启了电脑以后，如果不用这个自定义扫描器就不报错了。只要设置自定义扫描器就报错。

配置文件如下：

```yml
linters:
  enable:
    - ddd
linters-settings:
  custom:
    ddd:
      path: ./dddlint.so
      description: go linter
      original-url: 扫描器的源码地址
```

**Comment by xxpxxxxp** [comment]
从官方的配置看来，不需要特意设置enable ddd，custom lint会被自动加载
https://golangci-lint.run/usage/linters/#custom

你也可以试着跑一下 `golangci-lint run ./...` enable ddd应该是不行的

**Comment by zcyc** [comment]
好的， 我再看看吧。删掉也报错，不知道为啥了。

**Comment by xxpxxxxp** [comment]
Linux和Mac的ELF格式不一样，so包肯定也是不一样的，需要重新编译
最终能让`golangci-lint run ./...`跑过plugin就可以工作了

**Comment by zcyc** [comment]
您的新版本我这里彻底炸了，只要有配置文件就炸了。
我已经 disable 了 gocritic 也没用。
![Uploading image.png…]()

**Comment by xxpxxxxp** [comment]
抱歉，rollback中

**Comment by xxpxxxxp** [comment]
Rollback回上个版本了，抱歉带来了一系列的困扰

**Comment by zcjswx** [comment]
GOROOT为 1.17.x 版本时都会出现此问题，尝试了多个小版本。1.16和1.18都没有问题

**Comment by xxpxxxxp** [comment]
@zcjswx 最新版本的plugin `1.5.10` 依然有这个问题吗？

**Comment by zcjswx** [comment]
发现的确用的是旧版。删除了所有配置文件和plugin，再重新安装新版本，还是出错
`java.lang.Exception: golangci-lint panic: RunProcessResult(returnCode=2, stdout=, stderr=panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt`

IDEA 2021.3.3
go plugin 213.7172.6
go linter 1.5.10

**Comment by xxpxxxxp** [comment]
@zcjswx 创建了一个新issue #107 以免影响其他人，麻烦提供一下出错的 `go env`, `golangci-lint version`，如果code是开源的最好提供一下repo地址
