### ISSUE TITLE
Failed to Disvocer Linters

### ISSUE THREAD

**Issue by AlpJQ** [xxpxxxxp/intellij-plugin-golangci-lint#97]
![image](https://user-images.githubusercontent.com/38560140/147739649-735cc5b7-2418-4a47-a790-61db06a812a2.png)

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.9()
	github.com/go-critic/go-critic@v0.6.1/checkers/checkers.go:58 +0x4b4
) 
java.lang.Exception: Failed to Discover Linters: RunProcessResult(returnCode=2, stdout=, stderr=panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.9()
	github.com/go-critic/go-critic@v0.6.1/checkers/checkers.go:58 +0x4b4
)
	at com.ypwang.plugin.GolangCiOutputParser.parseLinters(GolangCiOutputParser.kt:34)
	at com.ypwang.plugin.form.GoLinterSettings.lambda$initializeLinters$17(GoLinterSettings.java:384)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-12-30 17:23:57,340 [1900493]  ERROR -                      go-linter - GoLand 2021.2.4  Build #GO-212.5457.54 
2021-12-30 17:23:57,340 [1900493]  ERROR -                      go-linter - JDK: 11.0.12; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2021-12-30 17:23:57,340 [1900493]  ERROR -                      go-linter - OS: Mac OS X 
2021-12-30 17:23:57,340 [1900493]  ERROR -                      go-linter - Plugin to blame: Go Linter version: 1.5.7 
2021-12-30 17:23:57,340 [1900493]  ERROR -                      go-linter - Last Action: EditorCopy 
2021-12-30 17:28:52,743 [2195896]   WARN - .AbstractProgressIndicatorBase - This progress indicator is indeterminate, this may lead to visual inconsistency. Please call setIndeterminate(false) before you start progress. class com.intellij.openapi.progress.util.ProgressWindow 
java.lang.IllegalStateException

**Comment by xxpxxxxp** [comment]
It's an upstream bug that should be resolved in the next version of `golangci-lint`, please temporarily disable `gocritic` linter until a new version of `golangci-lint` released.

Related:
https://github.com/go-critic/go-critic/issues/1157
https://github.com/go-critic/go-critic/issues/1126

In case you are stuck by the dialog and cannot unselect `gocritic`, please manually remove property
`go-enabled-linters` from file:
Win: %APPDATA%\JetBrains\Goland2021.3\options\other.xml
Mac: ~/Library/Application Support/JetBrains/Goland2021.3/options/other.xml
Linux: ~/.config/JetBrains/Goland2021.3/options/other.xml

For config file users, please disable `gocritic` in your config file directly.
Then the settings will be working.

**Comment by AlpJQ** [comment]
![image](https://user-images.githubusercontent.com/38560140/147743454-e3a76731-768b-4b1b-8ff7-a0436c94e65f.png)
配置文件中去除这个吗？我试了下不行

**Comment by AlpJQ** [comment]
我在~/Library/Application Support/JetBrains/Goland2021.3/options/other.xml找不到go-enabled-linters这个 property 呀～

**Comment by xxpxxxxp** [comment]
有config file的话就不会有这个property，在`.golangci.yaml`里disable gocritic就好
改完试下在当前目录下执行 `golangci-lint linters` 不报错就可以了

**Comment by AlpJQ** [comment]
这个东西不管了吗？
![image](https://user-images.githubusercontent.com/38560140/147745517-72ff46de-7763-4ea6-bda0-ac5e1da1ced3.png)

**Comment by AlpJQ** [comment]
没有报错，但打开tools还是有这个东西出现
![image](https://user-images.githubusercontent.com/38560140/147745635-da6aea9b-aa8c-4dfb-b749-f604e82df498.png)

**Comment by xxpxxxxp** [comment]
你有多个GO SDK环境吗？IDE里设置的GOROOT是否与bash里的不同？这个bug只在特定的go version下出现

**Comment by zcyc** [comment]
上一个版本的插件没这个问题。

**Comment by xxpxxxxp** [comment]
Rollback回上个版本了，抱歉带来了一系列的困扰
